import { NextResponse } from "next/server"
import { getTotalComparisonCount } from "@/data/pseo/comparisons"

const BASE_URL = "https://trackmysubscriptions.com"
const URLS_PER_CHUNK = 40000

// ── /sitemap-index.xml ───────────────────────────────────────────────
// A sitemap index that ties together:
//   • /sitemap.xml          → core pages (services, alternatives, pricing, glossary, etc.)
//   • /sitemaps/0 … /N      → comparison pages in 40 000-URL chunks

export async function GET() {
  const totalComparisons = getTotalComparisonCount()
  const totalChunks = Math.ceil(totalComparisons / URLS_PER_CHUNK)
  const now = new Date().toISOString()

  const xml = [
    `<?xml version="1.0" encoding="UTF-8"?>`,
    `<sitemapindex xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">`,
    // core pages sitemap (auto-generated by Next.js from sitemap.ts)
    `  <sitemap>`,
    `    <loc>${BASE_URL}/sitemap.xml</loc>`,
    `    <lastmod>${now}</lastmod>`,
    `  </sitemap>`,
    // comparison page chunks
    ...Array.from({ length: totalChunks }, (_, i) =>
      [
        `  <sitemap>`,
        `    <loc>${BASE_URL}/sitemaps/${i}</loc>`,
        `    <lastmod>${now}</lastmod>`,
        `  </sitemap>`,
      ].join("\n")
    ),
    `</sitemapindex>`,
  ].join("\n")

  return new NextResponse(xml, {
    headers: {
      "Content-Type": "application/xml",
      "Cache-Control": "public, max-age=86400, s-maxage=86400",
    },
  })
}
